// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhkcnxeocqhkeczxzljb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoa2NueGVvY3Foa2Vjenh6bGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Nzc3ODcsImV4cCI6MjA2NjU1Mzc4N30.skkwSDGeLwsrboDmzwPFv1-EzLE9YbqXN_fMH5biFxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);